version: 0.0
os: linuix
files: 
 - sourse: /
   destination: /home/ec2/express-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
       timeout: 3000
       runas: ec2-user
  ApplicationStart:
    -  location: scripts/application_start.sh
       timeout: 3000
       runas: ec2-user 
